# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "rooms" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
create table "talks" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"room_id" INTEGER NOT NULL,"title" VARCHAR NOT NULL);
alter table "talks" add constraint "fk_room_id" foreign key("room_id") references "rooms"("id") on update NO ACTION on delete CASCADE;

# --- !Downs

alter table "talks" drop constraint "fk_room_id";
drop table "talks";
drop table "rooms";

